server:
  port: 8092

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product
  application:
    name: ProductService

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/